apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: NodePort
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
